apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app-name }}-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 4 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: "{{ .Values.build.image}}:{{ .Values.build.tag }}"
        env:
        - name: NGINX_PORT
          value: "80"
        - name: NAME
          value: "Ort College"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-configmap-1